### ISSUE TITLE
Backend issue

### ISSUE THREAD

**Issue by devilkata** [KamenKadiyski/Rent_a_car#6]
2. Change data for already existing car - при веждане на ИД на колата с невалидено ИД, програмата не показва грешка и допуска потребителя да продължи напред..

**Comment by devilkata** [comment]
проверката за валидно ИД се активира, едва когато юзера иска да запамети промените.

**Comment by KamenKadiyski** [comment]
Коригирано - добавена е проверка при въвждане на ID на автомобила. Моля функцията да бъде тествана и да issue да бъде затворено ако всичко е ОК.

**Comment by devilkata** [comment]
тествано и работещо.
