### ISSUE TITLE
Scrap car

### ISSUE THREAD

**Issue by devilkata** [KamenKadiyski/Rent_a_car#7]
след въпроса - Are you sure you want to scrap this car? Y/N, и при двата входа връша към главното меню без никакво съобщение за юзера дали е направил успешно, това, което иска..

**Comment by devilkata** [comment]
същия сценарии с 3. Remove a car from the menu

**Comment by devilkata** [comment]
при вече изтрита кола или невалидно ИД , програмата не връща никакво съобщение, а спира.

**Comment by KamenKadiyski** [comment]
Коригирано. Моля да се тества отново и да се затвори issue ако всичко е ОК.

**Comment by devilkata** [comment]
тествано и работещо.
