### ISSUE TITLE
Client Menu: 2. Rent a Car

### ISSUE THREAD

**Issue by devilkata** [KamenKadiyski/Rent_a_car#9]
при въвжданети на невалидно ИД, програмата спира. Би било добре да има съобшение,че е навалиден и да пробва отново или да види листа с колите отново.

**Comment by KamenKadiyski** [comment]
Извършени корекци на функциите за наемане и връщане на автомобил. Ако се въведе несъществуващ автомобил извежда съобщение за грешка. Но това не извършва проверка за валидност на въведените символи. Ако приема всякакви символи за ID на автомобила е необходимо frontend да обърне внимание и да коригира сорс-кода
